/**
 * Sample API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Team { 
    name: string;
    city: string;
    stadium: string;
    ranking: number;
    budget: number;
}

